create table stock (id integer generated by default as identity, current_price NUMERIC(19,8) not null, description varchar(255), last_update timestamp not null, name varchar(50) not null, primary key (id));
create table stock_exchange (id integer generated by default as identity, description varchar(255), live_in_market boolean, name varchar(50) not null, primary key (id));
create table stock_exchange_stock_mapping (exchange_id integer not null, stock_id integer not null, primary key (exchange_id, stock_id));

alter table stock add constraint UK9fjf4aj1d5f2m6wi2uqmdan0a unique (name);
alter table stock_exchange add constraint UKcorjusnywadeyc44m8fhvg8mc unique (name);
alter table stock_exchange_stock_mapping add constraint FKi98flonjrmhhmrcmb2t0um8tn foreign key (stock_id) references stock;
alter table stock_exchange_stock_mapping add constraint FKp77fxayypp0fotgcyvkddvxj1 foreign key (exchange_id) references stock_exchange;
